# Generated by Django 4.1.1 on 2022-09-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True, upload_to="profile_pics/%Y/%m", verbose_name="profile_pic"
            ),
        ),
    ]
