# Generated by Django 4.1.1 on 2022-09-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0002_remove_user_profile_picture_user_profile_pic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="caption",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="post_pics/%Y/%m", verbose_name="post_picture"
            ),
        ),
    ]
