# Generated by Django 4.1.1 on 2022-10-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0003_rename_caption_post_description_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="post_pics", verbose_name="post_picture"
            ),
        ),
    ]
